packages: []
pmOnFail: error
saveExact: true
minimumReleaseAge: 10080
trustPolicy: no-downgrade
patchedDependencies:
  '@wxt-dev/browser@0.3.0': patches/@wxt-dev__browser@0.3.0.patch
  wxt@0.21.4: patches/wxt@0.21.4.patch
